import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useEffect, useState, useRef, useLayoutEffect } from 'react';
import Header from '../components/Header';
import {Button, Modal, Box } from '@mui/material';
import MediaCard from '../components/MediaCard';
import EnableColorOnDarkAppBar from '../components/BottomNavigation';

const style = {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  width: 400,
  boxShadow: 30,
  p: 4,
};

export default function Home() {

  const [data, setData] = useState();
  const [open, setOpen] = useState(false);
  const [image, setImage] = useState("");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const carousel = useRef(null);
  const carouselTwo = useRef(null);
  const carouselThree = useRef(null);
  const [width, height] = useWindowSize();

  function useWindowSize() {
    const [size, setSize] = useState([0, 0]);

    useLayoutEffect(() => {

      function updateSize() {
        setSize([window.innerWidth, window.innerHeight]);
      }

      window.addEventListener('resize', updateSize);
      updateSize();
      return () => window.removeEventListener('resize', updateSize);
    }, []);

    return size;
  }

  useEffect(() => {
    fetch('http://localhost:3000/api/hello')
      .then((response) => response.json())
      .then(setData);
  }, []);

  const handleLeftClick = (e) => {
    e.preventDefault();
    carousel.current.scrollLeft -= carousel.current.offsetWidth;
  };

  const handleRightClick = (e) => {
    e.preventDefault();

    carousel.current.scrollLeft += carousel.current.offsetWidth;
  };

  const handleLeftClickTwo = (e) => {
    e.preventDefault();
    carouselTwo.current.scrollLeft -= carouselTwo.current.offsetWidth;
  };

  const handleRightClickTwo = (e) => {
    e.preventDefault();

    carouselTwo.current.scrollLeft += carouselTwo.current.offsetWidth;
  };

  const handleLeftClickThree = (e) => {
    e.preventDefault();
    carouselThree.current.scrollLeft -= carouselThree.current.offsetWidth;
  };

  const handleRightClickThree = (e) => {
    e.preventDefault();

    carouselThree.current.scrollLeft += carouselThree.current.offsetWidth;
  };

  if (!data || !data.length) return null;

  function handleOpen(img,title, description) {
    setImage(img)
    setTitle(title)
    setDescription(description)
    setOpen(true)
  }

  function handleClose() {
    setImage("")
    setTitle("")
    setDescription("")
    setOpen(false)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section className={styles.one_section}>
          <div className={styles.box}>
            <div className={styles.title}>
              <Image src="/MovieName.png" alt="Vercel Logo" width={408} height={105} />
            </div>

            <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, autem perferendis dolore nostrum quo illo animi necessitatibus deleniti, quaerat omnis possimus eum facere sapiente qui, accusantium nisi ex nobis quis.</h3>

            <div className={styles.grid_btns} style={{position: 'relative'}}>
              <a href="https://nextjs.org/docs">
                <div className={styles.btn}>
                  <Image src="/Play.png" alt="Vercel Logo" width={32} height={32} />
                  <span>Assistir</span>
                </div>
              </a>
              <a>
              <div className={styles.btn} style={{ backgroundColor: 'rgba(255, 255, 255, 0.3)', color: 'white'}}>
                <Image src="/Detail.png" alt="Vercel Logo" width={32} height={32} />
                <span>Saber mais</span>
              </div>
              </a>
              <div style={{position: 'absolute', right: '-40px'}}>
              <Image src="/Top10Badge.png" alt="Vercel Logo" width={30} height={30} />
              </div>
            </div>

            <h4>Populares BseenFlix</h4>
            <div className={styles.container_movies_h}>
              <div >
                <img src="/ArrowRight.png" alt="Vercel Logo" width={20} height={16} onClick={handleLeftClick}/>
              </div>
              <div className={styles.carousel} ref={carousel}>
                  {data.map((item) => {
                      const { id, title, image, description } = item;
                      return (
                        <div className={styles.item} key={id} onClick={() => handleOpen(image,title, description)}>
                          <div className={styles.image}>
                              <img src={image} alt={name} />
                          </div>
                        </div>
                      );
                  })}
              </div>
              <div>
                <img src="/ArrowLeft.png" alt="Vercel Logo" width={20} height={16} onClick={handleRightClick}/>
              </div>
            </div>
          </div>
          
        </section>

        <section className={styles.two_section}>
          <div className={styles.box}>
            <h4>Comédia BseenFlix</h4>
            <div className={styles.container_movies}>
              <div >
                <img src="/ArrowRight.png" alt="Vercel Logo" width={20} height={16} onClick={handleLeftClickTwo}/>
              </div>
              <div className={styles.carousel} ref={carouselTwo}>
                  {data.map((item) => {
                      const { id, title, image, description } = item;
                      return (
                        <div className={styles.item} key={id} onClick={() => handleOpen(image,title, description)}>
                          <div className={styles.image}>
                              <img src={image} alt={name} />
                          </div>
                        </div>
                      );
                  })}
              </div>
              <div>
                <img src="/ArrowLeft.png" alt="Vercel Logo" width={20} height={16} onClick={handleRightClickTwo}/>
              </div>
            </div>

            <h4>Séries BseenFlix</h4>
            <div className={styles.container_movies}>
              <div >
                <img src="/ArrowRight.png" alt="Vercel Logo" width={20} height={16} onClick={handleLeftClickThree}/>
              </div>
              <div className={styles.carousel} ref={carouselThree}>
                  {data.map((item) => {
                      const { id, title, image, description } = item;
                      return (
                          <div className={styles.item} key={id} onClick={() => handleOpen(image, title, description)}>
                            <div className={styles.image}>
                                <img src={image} />
                            </div>
                          </div>
                      );
                  })}
              </div>
              <div>
                <img src="/ArrowLeft.png" alt="Vercel Logo" width={20} height={16} onClick={handleRightClickThree}/>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Modal
        open={open}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box sx={style}>
          <MediaCard img={image} title={title} description={description}/>
        </Box>
      </Modal>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          BseenFlix
        </a>
      </footer>
    </div>
  )
}
